### ISSUE TITLE
How to handle error propagation

### ISSUE THREAD

**Issue by abourget** [klauspost/shutdown2#12]
I'm interesting in knowing the source of the first error, the first cause of the shutdown.. how do you handle `error` propagation with this system?

Great work, thanks a lot :)

**Comment by abourget** [comment]
`ShutdownWithError(err error)` and `WaitError() error` ?

**Comment by klauspost** [comment]
In general I think I would just go for a function in your own package, like

```Go
func ShutdownWithError(err error) {
  shutdown.Shutdown()
  log.Fatal("Exit with error: ", err.Error())
}
```
Or something similar that suits your needs.

**Comment by abourget** [comment]
Ok, thanks!
