### ISSUE TITLE
Don't log to stdout per default

### ISSUE THREAD

**Issue by muesli** [klauspost/shutdown2#8]
I have a feeling logging to stdout should only be "opt-in" for a library. Let the user specify a logger if they want one, otherwise print to ioutil.Discard.

**Comment by muesli** [comment]
Yeah, I already passed in my own logger - I do still consider it good style for a library to keep quiet unless asked to.

I kinda understand your reasoning, but may I ask what you consider "too late" in this case?
Is this library already used in production now?
Only for this release cycle / major version?
Do you plan "proper" releases in the future?

**Comment by klauspost** [comment]
>Is this library already used in production now?

Yes, and I would not change default behavior unless it is a major inconvenience.

>Only for this release cycle / major version?

If major issues comes up, then I would consider it.

>Do you plan "proper" releases in the future?

Not at the moment. I consider it "properly" released :)
